import json
import os
import pathlib
import re
import tempfile
import unittest

import i18n


LOCALES = pathlib.Path(__file__).resolve().parent.parent / "i18n" / "locales"
REPORT_TEMPLATE = pathlib.Path(__file__).resolve().parent.parent / "templates" / "report.html"

# Words that betray one language leaking into the other.
_DUTCH = ("Advies", "Probleem", "Hertesten", "Referentie", "Beveiligingsrapport",
          "Scandatum", "Gegenereerd", "oplossen")
_ENGLISH = ("Advice", "Problem", "Retest", "Reference", "Security Report",
            "Scan date", "Generated by")


class LocaleFileTests(unittest.TestCase):
    """The report mixed languages: English recommendation text under Dutch
    headings, and the Dutch word "advies" even appeared inside otherwise
    English sentences.
    """

    def _load(self, locale):
        return json.loads((LOCALES / f"{locale}.json").read_text(encoding="utf-8"))

    def test_locales_have_identical_key_sets(self):
        def flatten(obj, prefix=""):
            keys = set()
            for k, v in obj.items():
                path = f"{prefix}{k}"
                if isinstance(v, dict):
                    keys |= flatten(v, path + ".")
                else:
                    keys.add(path)
            return keys

        en, nl = flatten(self._load("en")), flatten(self._load("nl"))
        self.assertEqual(en - nl, set(), "keys missing from nl.json")
        self.assertEqual(nl - en, set(), "keys missing from en.json")

    def test_report_section_exists_in_both(self):
        for locale in ("en", "nl"):
            self.assertIn("report", self._load(locale))

    def test_no_english_left_in_the_dutch_report_strings(self):
        nl = self._load("nl")["report"]
        for key, value in nl.items():
            for word in ("Advice", "Retest", "Problem"):
                self.assertNotIn(word, value, f"nl.report.{key} contains {word!r}")

    def test_no_dutch_left_in_the_english_report_strings(self):
        en = self._load("en")["report"]
        for key, value in en.items():
            for word in ("Advies", "Probleem", "Hertesten"):
                self.assertNotIn(word, value, f"en.report.{key} contains {word!r}")


class TemplateHardcodingTests(unittest.TestCase):

    def test_report_template_has_no_hardcoded_dutch(self):
        # Jinja expressions may name keys like report.advice_heading; only the
        # literal text between tags matters.
        html = REPORT_TEMPLATE.read_text(encoding="utf-8")
        stripped = re.sub(r"\{\{.*?\}\}|\{%.*?%\}", "", html, flags=re.S)
        for word in _DUTCH:
            self.assertNotIn(word, stripped, f"hardcoded Dutch {word!r} in report.html")


class RenderedReportTests(unittest.TestCase):
    """A rendered report must be in one language, whichever is selected."""

    def setUp(self):
        self.tempdir = tempfile.TemporaryDirectory()
        os.environ["DOMAINLENS_DB"] = os.path.join(self.tempdir.name, "i18n.db")
        os.environ["DOMAINLENS_DISABLE_SCHEDULER"] = "1"
        import importlib
        import db as db_module
        import app as app_module
        self.db = importlib.reload(db_module)
        self.db.init_db()
        self.app_module = importlib.reload(app_module)
        self.client = self.app_module.app.test_client()
        self.scan_id = self.db.save_scan(
            "example.com", {"domain": "example.com", "dnssec": {"signed": False}})

    def tearDown(self):
        self.tempdir.cleanup()
        for key in ("DOMAINLENS_DB", "DOMAINLENS_DISABLE_SCHEDULER"):
            os.environ.pop(key, None)

    def _report(self, locale):
        self.client.post("/api/locale", json={"locale": locale})
        return self.client.get(f"/report/{self.scan_id}").data.decode()

    def test_english_report_has_no_dutch_chrome(self):
        body = self._report("en")
        for word in _DUTCH:
            self.assertNotIn(word, body, f"Dutch {word!r} in the English report")

    def test_dutch_report_has_no_english_chrome(self):
        body = self._report("nl")
        for word in _ENGLISH:
            self.assertNotIn(word, body, f"English {word!r} in the Dutch report")

    def test_both_locales_actually_render(self):
        self.assertIn("Security Report", self._report("en"))
        self.assertIn("Beveiligingsrapport", self._report("nl"))


class RetestTextTests(unittest.TestCase):
    """The default retest guidance had a Dutch word embedded in an English
    sentence ("confirm this advies item is no longer listed").
    """

    def test_no_dutch_in_generated_retest_text(self):
        import recommendations
        for category in ("DNS", "Email", "Web", "TLS", "Network", "OSINT", "", "Other"):
            text = recommendations._default_retest(category, "some finding", "example.com")
            self.assertNotIn("advies", text.lower(), f"category {category!r}: {text}")


if __name__ == "__main__":
    unittest.main()
